version: "3"
services:
    elasticsearch:
        image: elasticsearch:7.7.0
        container_name: elasticsearch
        environment:
            - discovery.type=single-node
        volumes:
            - /opt/elasticsearch/first:/usr/share/elasticsearch/data
        ports:
            - 9200:9200
        networks:
            - elastic
        labels:
            - co.elastic.logs/module=elasticsearch
            - co.elastic.metrics/module=elasticsearch
    kibana:
        image: docker.elastic.co/kibana/kibana:7.7.0
        container_name: kibana
        ports:
            - 5601:5601
        depends_on:
            - elasticsearch
        environment:
            ELASTICSEARCH_URL: http://localhost:9200
            ELASTICSEARCH_HOSTS: http://localhost:9200
        networks:
            - elastic
networks:
    elastic:
      driver: bridge  